### ISSUE TITLE
Extension 17 unsupported

### ISSUE THREAD

**Issue by terrydavis903** [Danny-Dasilva/CycleTLS#100]
Extension 17 "status_request_v2" isn't supported right now. New chrome seems to use this, would be a nice feature.

**Comment by Danny-Dasilva** [comment]
The latest release [1.0.21](https://github.com/Danny-Dasilva/CycleTLS/pull/105) has temporary support for extension 17, if this does not work please feel free to reopen this with an example user agent. I do not believe the latest version of chrome uses this (seen below) but the temporary extension should now work. 

https://github.com/Danny-Dasilva/CycleTLS/blob/c84d740b4757c7bf80168047d1c7224012eafb15/tests/frameHeader.test.ts#L7
