### ISSUE TITLE
HTTP2 and JA3 Are detectable

### ISSUE THREAD

**Issue by FloppaFriday** [Danny-Dasilva/CycleTLS#101]
### Description

Some pages detect cylcetls based on the tls and http2 behaviour by the library.
TLS:
Cycletls uses "TLS_GREASE" In addition to the other cipher suites and also has the padding extension. That firefox for ex. doesnt send.

HTTP2:
cycletls doesnt send the PRIORITY frames as opposed to a normal browser.

output from both browser and cycletls:
Cycletls: https://pastebin.com/bkUzmiaG
Browser: https://pastebin.com/9etfRBXB

to replicate:
https://tls.peet.ws/api/all

### Issue Type

Others

### Operating System

Windows 10

### Node Version

Other

**Comment by Danny-Dasilva** [comment]
The latest release [1.0.21](https://github.com/Danny-Dasilva/CycleTLS/pull/105) has a specific test with the latest version of chrome and firefox which checks ja3, useragent, and the connection settings. [You can see it here ](https://github.com/Danny-Dasilva/CycleTLS/blob/main/tests/frameHeader.test.ts). That being said I cannot reproduce this. Grease extensions and proper frame headers should be set (I am aware there is a frame header issues specifically on Mac when using chrome connection headers. 

Keep in mind User-Agent is parsed to know which connection headers to send and whether or not to set GREASE. 

If you still find this issue occurring feel free to re-open

**Comment by FloppaFriday** [comment]
Hi im still facing the exact same issue. Nothing has changed at all compared to before. Cycletls still sends GREASE, padding and doesnt send any http priority frames wich messes up the http2 fingerprint.
Especially the HTTP2 issue is an problem because it causes detection. Frames send are incorrect for example the settings frame sends entirely different content as opposed to the browser.
Because of that the values that tls.peet.ws calls akamai_fingerprint and akamai_fingerpring_hash are both different from the actual browser. Im able to reproduce this behaviour of cycletls for both chrome and firefox
Im running the machine on windows 10 if that helps

**Comment by FloppaFriday** [comment]
additional to that newer chrome versions are returning Extension {{ 17513 }} is not Supported by CycleTLS please raise an issue when an attempt at an request is made

**Comment by FloppaFriday** [comment]
Also an interesting issue to look into would be the fact that some useragents arent sending any headers for example requesting tls.peet.ws with "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36" as a header returns the response "no useragent"
