### ISSUE TITLE
Could you give me an example of using cookies?

### ISSUE THREAD

**Issue by Yeqishen** [Danny-Dasilva/CycleTLS#102]
### Description

Go version : 1.18.3 linux/amd64

I'm a beginner of go, could you show an example of using cookies ? I couldn't find any useful tips on the Internet about the CycleTlS module. I would be very grateful for that.

![image](https://user-images.githubusercontent.com/91174990/172793729-649a2d00-0ff6-4084-8c2e-598ec4ad8e52.png)

### Issue Type

Others

### Operating System

Linux

### Node Version

Other

### Golang Version

Other

**Comment by Danny-Dasilva** [comment]
https://github.com/Danny-Dasilva/CycleTLS#how-do-i-set-cookies, I'll make an example for CookieJar in Golang with the next release
