### ISSUE TITLE
uTlsConn.Handshake() error: local error: tls: unexpected message

### ISSUE THREAD

**Issue by White2001Offl** [Danny-Dasilva/CycleTLS#103]
### Description

I'm getting a weird error
`uTlsConn.Handshake() error: local error: tls: unexpected message`

Also, it happens in specific Ja3 or idk
this was the ja3 `771,4865-4866-4867-49196-49195-52393-49200-49199-52392-49162-49161-49172-49171-157-156-53-47-49160-49170-10,0-23-65281-10-11-16-5-13-18-51-45-43-27-21,29-23-24-25,0`

Mainly it happens with 17513 Extension. I guess its related to that

### Issue Type

Bug

### Operating System

Windows 10, Mac OS

### Golang Version

Go 16.x

### Relevant Log Output

```shell
-> \nPost \"https://someurl.com\": uTlsConn.Handshake() error: local error: tls: unexpected message
```

**Comment by KawaCode** [comment]
@Danny-Dasilva Please check this out, because of this akamai is somehow detecting users.

**Comment by ejames17** [comment]
can confirm same issue here

**Comment by KawaCode** [comment]
Somehow akamai is detecting users depending on tls library, i dont know the issue yet, i am researching.

**Comment by ejames17** [comment]
Weirdly enough  the latest version seems to get detected but version 0.0.15-alpha.0 still works for me in production @KawaCode

**Comment by White2001Offl** [comment]
I'll create a new issue about this
