### ISSUE TITLE
undefined: tls.FakeCertCompressionAlgsExtension

### ISSUE THREAD

**Issue by KawaCode** [Danny-Dasilva/CycleTLS#104]
### Description

github.com/Danny-Dasilva/CycleTLS/cycletls/utils.go:234:15: undefined: tls.FakeCertCompressionAlgsExtension

### Issue Type

Bug

### Operating System

Linux

### Node Version

Other

### Golang Version

Other

### Relevant Log Output

```shell
github.com/Danny-Dasilva/CycleTLS/cycletls/utils.go:234:15: undefined: tls.FakeCertCompressionAlgsExtension
```

**Comment by Danny-Dasilva** [comment]
the latest release [1.0.21](https://github.com/Danny-Dasilva/CycleTLS/pull/105) has updates to this extension so this should be resolved now.
