### ISSUE TITLE
Return Response URL

### ISSUE THREAD

**Issue by david-jng** [Danny-Dasilva/CycleTLS#121]
### Description

I would like to see the response URL and not only status code, body and headers.

### Issue Type

Feature Request

### Operating System

Windows 10

### Node Version

Node 16.x

**Comment by Danny-Dasilva** [comment]
Final Respose is added to the response object in both golang and JS

js example with disableRedirect
https://github.com/Danny-Dasilva/CycleTLS/blob/main/tests/disableRedirect.test.ts

golang example with disable redirect
https://github.com/Danny-Dasilva/CycleTLS/blob/main/cycletls/tests/integration/disable_redirect_test.go
