### ISSUE TITLE
Error Processing Request - Permission Denied

### ISSUE THREAD

**Issue by IliasElbarnoussi** [Danny-Dasilva/CycleTLS#129]
### Description

The error occurs occasionally, after a few restarts the error is gone and it runs fine again without having changed anything. 

**Request code snippet:**

    const initCycleTLS = require("cycletls")
    const cycleTLS = await initCycleTLS();

        const response = await cycleTLS(`https://XXX-XXX.XXXX.com/api/v1/analytics/orders/recent box_condition=1&count=20&is_consigned=0`, {
        url: `https://XXX-XXX.XXXX.com/api/v1/analytics/orders/recent?box_condition=1&count=20&is_consigned=0`,
        method: "get",
        headers: {  "accept":"application/json", "accept-language":"nl-NL,nl;q=0.9"},
        ja3: '771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,0-23-65281-10-11-35-16-5-13-18-51-45-43-27-21,29-23-24,0',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko)',
        timeout: 7,
        proxy: 'http://XXXX:XXXX@XXXX:80'
        }, "get").catch((err) => {
            console.log(err);
        });
        
        return response.body
        }

### Issue Type

Support

### Operating System

Linux

### Node Version

Node 16.x

### Relevant Log Output

```shell
Error Processing Request (please open an issue https://github.com/Danny-Dasilva/CycleTLS/issues/new/choose) -> /bin/sh: 1: /usr/local/BrickMonitorV2/node_modules/cycletls/dist/index: Permission denied

node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

Error: kill ESRCH
    at process.kill (node:internal/process/per_thread:220:13)
    at /usr/local/BrickMonitorV2/node_modules/cycletls/dist/index.js:59:25
    at new Promise (<anonymous>)
    at cleanExit (/usr/local/BrickMonitorV2/node_modules/cycletls/dist/index.js:58:13)
    at Socket.<anonymous> (/usr/local/BrickMonitorV2/node_modules/cycletls/dist/index.js:86:19)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  errno: -3,
  code: 'ESRCH',
  syscall: 'kill'
}
```

**Comment by Danny-Dasilva** [comment]
Closing as this is stale, feel free to reopen with a request example that can be tested against. If privacy is a concern you can email me the url or dm it to me on discord. Ideally this issue has been addressed by the latest fixes but I have no way to test.
