### ISSUE TITLE
Connections stay open.

### ISSUE THREAD

**Issue by dropout1337** [Danny-Dasilva/CycleTLS#137]
### Description

When using cycletls it creates a new client every time and don't seem to close the connection resulting in lots of open connections not being used, when using proxies with thread limits it'l reach the thread limit quite fast.

This can be fixed by adding `resp.Body.Close()` and `DisableKeepAlives: true` to the transport.

### Issue Type

Bug, Performance

### Operating System

Windows 10

### Golang Version

Go 17.x

**Comment by Its-Vichy** [comment]
+ Add feature to transport that will allow us to add custom curve

**Comment by Danny-Dasilva** [comment]
I'm looking into a way to reuse connections. But currently we do close the response body https://github.com/Danny-Dasilva/CycleTLS/blob/c84d740b4757c7bf80168047d1c7224012eafb15/cycletls/index.go#L180
I'll add in `DisableKeepAlives` as a temporary fix but long term I'd like to reuse the entire client.

**Comment by Danny-Dasilva** [comment]
DisableKeepAlives has been added to the transport
