### ISSUE TITLE
Attribution

### ISSUE THREAD

**Issue by seankovacs** [Danny-Dasilva/CycleTLS#15]
Can you add correct attribution as most of this code is from https://github.com/zedd3v/mytls.

**Comment by Danny-Dasilva** [comment]
Hey @seankovacs this repo is currently under construction (and is my personal repo),  I will add attribution once a release is ready. This repo is already fundamentally different on the golang side compared to mytls with the only similarities being JA3 token parsing which mytls borrows from [JA3Transport](https://github.com/cucyber/JA3Transport). This token parsing is currently under revision ([see issue link](https://github.com/Danny-Dasilva/CycleTLS/issues/14)) as it does not support Http2 servers (see [1](https://github.com/zedd3v/mytls/issues/7) [2](https://github.com/zedd3v/mytls/issues/5) [3](https://github.com/refraction-networking/utls/issues/72)). The Js/Ts side will also be undergoing major revisions as I add npm install support to different clients and finish CI/CD integration. 

Seeing as how the repo directly states it is currently under construction /multiple tasks open in the [Projects](https://github.com/Danny-Dasilva/CycleTLS/projects/1) /no repo liscence /minimal and non-functional documentation it seems weird to be asking for attribution.

 I will be happy to private the repo until it is ready for release and add attribution then.

**Comment by seankovacs** [comment]
I'll leave that up to you.
