### ISSUE TITLE
pre_shared_key never been sent

### ISSUE THREAD

**Issue by cheneyhu82** [Danny-Dasilva/CycleTLS#152]
### Description

compare with chrome requests, CycleTLS nver sends CycleTLS. and i found there is a comment about this

	`"41": &utls.GenericExtension{Id: 41}, //FIXME pre_shared_key`

### Issue Type

Feature Request

### Operating System

Windows 10

### Node Version

Node 16.x

### Golang Version

Go 14.x

**Comment by Danny-Dasilva** [comment]
This should now be fixed as of the latest release 
https://github.com/Danny-Dasilva/CycleTLS/blob/f6c898f1bb298f3d6dd7fcfdfb531d950cc587a3/cycletls/utils.go#L303
