### ISSUE TITLE
application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by bkaryagdi** [Danny-Dasilva/CycleTLS#155]
### Description

How can i send "application/x-www-form-urlencoded" post methods

**Comment by Danny-Dasilva** [comment]
Similar to https://github.com/Danny-Dasilva/CycleTLS/issues/89, I'll include this in the next release

**Comment by Danny-Dasilva** [comment]
Official Support added in the latest release
https://github.com/Danny-Dasilva/CycleTLS#how-do-i-send-a-applicationx-www-form-urlencoded-post-request
