### ISSUE TITLE
Memory leaks builded package on Docker container

### ISSUE THREAD

**Issue by mminovv** [Danny-Dasilva/CycleTLS#157]
### Description

@Danny-Dasilva Hi, Great project. I too have encountered this problem. I have a memory leak. I'm building cycletls on Docker with Nodejs and connecting to it via ws. And I don't understand why there is a leak inside the cycletls container. Why is this happening?

### Issue Type

Performance

### Operating System

Linux

### Node Version

Node 16.x

**Comment by Cyhlnj** [comment]
me too

**Comment by mminovv** [comment]
>  me too
> 
> 

Are you solved this problem?(

**Comment by Danny-Dasilva** [comment]
I need additional information. How are you connecting to the container. Cycletls by default is built to scale to the available memory on the system, any additional information you have to reproduce would be useful.

**Comment by jellyb0y** [comment]
Hi! Me too! 
So, I can provide more information.

Env: docker container node:19, cycletls built in nodejs package.
Also I use proxies to avoid cloudflare bans.
My code do about 160 requests per second and after 3 minutes memory leak is about 3gb while nodejs process is 250MB only.

**Comment by Danny-Dasilva** [comment]
this should now be addressed in version [1.0.22](https://github.com/Danny-Dasilva/CycleTLS/pull/266). Multiple nodejs and golang fixes were done so if this persists feel free to re-open this issue
