### ISSUE TITLE
uTlsConn.Handshake() error: remote error: tls: error decoding message

### ISSUE THREAD

**Issue by Tsyklop** [Danny-Dasilva/CycleTLS#160]
### Description

I use last version of cycle-tls. Site works on http/2

**JA3**: 771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-156-157-47-53,0-23-65281-10-11-35-16-5-34-51-43-13-45-28-21,29-23-24-25-0-1,0
**User-Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0    

**Headers:**

"accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
"accept-encoding": "gzip, deflate, br"
"accept-language": "ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3"
"host": "site.de"
"sec-fetch-dest": "document"
"sec-fetch-mode": "navigate"
"sec-fetch-site": "none"
"sec-fetch-user": "?1"
"TE": "trailers"
"upgrade-insecure-requests": "1"
"user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0"

https://tools.scrapfly.io/api/fp/ja3?extended=1 gives me next ja3 token:
772,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-156-157-47-53,0-23-65281-10-11-16-5-34-51-43-13-45-28-41,0-1-2-3-4-5,0    

https://tls.peet.ws/api/clean gives me next ja3 token:   
771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-156-157-47-53,0-23-65281-10-11-35-16-5-34-51-43-13-45-28-21,29-23-24-25-0-1,0

ja3 tokens above not working - tls: error decoding message.

But the next token works, but its for Chrome:    

771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,0-23-65281-10-11-35-16-5-13-18-51-45-43-27-17513-21,29-23-24,0

**Golang Version**: 1.18.5

### Issue Type

Bug

### Operating System

Windows 10

### Node Version

Node 14.x

### Golang Version

Other

### Relevant Log Output

```shell
Get "https://site.de/ru-de/": uTlsConn.Handshake() error: remote error: tls: error decoding message
```

**Comment by undercat013** [comment]
Try removing the value "31". It worked for me

**Comment by jalbertmayor** [comment]
> But the next token works, but its for Chrome:
>771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,0-23-65281-10-11-35-16-5-13-18-51-45-43-27-17513-21,29-23-24,0

it's weird to get 771, it can't be chrome, 771 is tls 1.2, chrome is tls 1.3 (772). most of online ja3 fp are out of date, you should check https://scrapfly.io/web-scraping-tools/ja3-fingerprint which seems to be the most accurate

**Comment by itschasa** [comment]
when trying to connect to `https://discord.com/api/v9/experiments`, with tls1.3, i get the same error.
i used the ja3 from the site you mentioned above. im not sure what i can do to fix it

`{
  ja3: '772,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,0-23-65281-10-11-35-16-5-13-18-51-45-43-27-17513-41,29-23-24,0',
  headers: {
    Accept: '*/*',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'en-GB',
    Referer: 'https://discord.com/',
    'Sec-Ch-Ua': '"Chromium";v="106", "Google Chrome";v="106", "Not;A=Brand";v="99"',
    'Sec-Ch-Ua-Mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-origin',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.5249.91 Safari/537.36',
    'X-Track': 'eyJvcyI6IldpbmRvd3MiLCJicm93c2VyIjoiQ2hyb21lIiwiZGV2aWNlIjoiIiwic3lzdGVtX2xvY2FsZSI6ImVuLUdCIiwiYnJvd3Nlcl91c2VyX2FnZW50IjoiTW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEwNi4wLjUyNDkuOTEgU2FmYXJpLzUzNy4zNiIsImJyb3dzZXJfdmVyc2lvbiI6IjEwNi4wLjUyNDkuOTEiLCJvc192ZXJzaW9uIjoiMTAiLCJyZWZlcnJlciI6IiIsInJlZmVycmluZ19kb21haW4iOiIiLCJyZWZlcnJlcl9jdXJyZW50IjoiIiwicmVmZXJyaW5nX2RvbWFpbl9jdXJyZW50IjoiIiwicmVsZWFzZV9jaGFubmVsIjoic3RhYmxlIiwiY2xpZW50X2J1aWxkX251bWJlciI6OTk5OSwiY2xpZW50X2V2ZW50X3NvdXJjZSI6bnVsbH0='
  },
  timeout: 10
}`
`{
  status: 0,
  body: '-> \n' +
    'Get "https://discord.com/api/v9/experiments": uTlsConn.Handshake() error: remote error: tls: error decoding message',
  headers: {}
}`

**Comment by itschasa** [comment]
i found a fix for myself

make sure you dont have `41` in your SSLExtension part of the ja3.
41 = pre_shared_key
cycletls cant use this when it doesnt know/have the shared key already
i don't know whether its ja3 will update to show it does after its got a shared_key

**Comment by 89z** [comment]
772 is never a valid number for TLS

**Comment by yang520f** [comment]
> 772 is never a valid number for TLS

I think It's wired. When I access to https://scrapfly.io/web-scraping-tools/ja3-fingerprint, I truly get 772, I failed to use it in cycle-tls for I get the same wrong msg. However, it's ok when I use 771.

**Comment by 89z** [comment]
@yang520f  see the discussion in this linked issues, to why 772 is never a valid number. Especially this comment:

https://github.com/Danny-Dasilva/CycleTLS/issues/169#issuecomment-1296068342

**Comment by Danny-Dasilva** [comment]
I made some updates to what happens when you pass 771 and added support for the pre-shared key extension. This should no longer be an issue but feel free to reopen if you encounter anything

https://github.com/Danny-Dasilva/CycleTLS/blob/f6c898f1bb298f3d6dd7fcfdfb531d950cc587a3/cycletls/utils.go#L303
