### ISSUE TITLE
Request body not being sent

### ISSUE THREAD

**Issue by CSCreatez** [Danny-Dasilva/CycleTLS#195]
### Description

Hello, on some sites I have noticed the request body does not get sent. An example is below:

```go
package main

import (
	"log"
	"github.com/Danny-Dasilva/CycleTLS/cycletls"
)

func main() {

	client := cycletls.Init()

	response, err := client.Do("https://yahoo.com", cycletls.Options{
		Body: "testing=test",
		Ja3: "771,49195-49196-52393-49199-49200-52392-49171-49172-156-157-47-53,65281-0-23-35-13-5-16-11-10,29-23-24,0",
		UserAgent: "w/e",
	}, "POST");
	if err != nil {
		log.Print("Request Failed: " + err.Error())
	}
	log.Println(response.Body)
}
```

`Go Version: 18`

Debugged with Charles, shows the request and content-length being sent, but not the body. If I switch the url to, for example, google.com; the request body appears again. This also happens on some other sites

### Issue Type

Bug, Support

### Operating System

Windows 10

### Node Version

Node 16.x

### Golang Version

Other

**Comment by yoni13** [comment]
How to solve this.?
