### ISSUE TITLE
Cycle tls said to report 

### ISSUE THREAD

**Issue by takefy-dev** [Danny-Dasilva/CycleTLS#197]
### Description

Error Processing Request (please open an issue https://github.com/Danny-Dasilva/CycleTLS/issues/new/choose) -> 2022/12/14 16:31:47 listen tcp :9119: bind: address already in use

### Node Version

None

### Golang Version

None

**Comment by Danny-Dasilva** [comment]
This means the cycletls process isn't closed. Meaning you started the program somewhere and didn't close it out. I would assign a new port when initializing the class and this error should go away.
