### ISSUE TITLE
        github.com/Danny-Dasilva/utls@v0.0.0-20220418175931-f38e470e04f2: reading https://goproxy.io/github.com/%21danny-%21dasilva/utls/@v/v0.0.0-20220418175931-f38e470e04f2.mod: 404 Not Found

### ISSUE THREAD

**Issue by 72min** [Danny-Dasilva/CycleTLS#202]
### Description

        github.com/Danny-Dasilva/utls@v0.0.0-20220418175931-f38e470e04f2: reading https://goproxy.io/github.com/%21danny-%21dasilva/utls/@v/v0.0.0-20220418175931-f38e470e04f2.mod: 404 Not Found

### Node Version

None

### Golang Version

None

**Comment by Danny-Dasilva** [comment]
what command are you running that raises this error?

**Comment by Danny-Dasilva** [comment]
This issue should be addressed as this module no longer uses my fork of utls
