### ISSUE TITLE
Discord Community

### ISSUE THREAD

**Issue by optionsx** [Danny-Dasilva/CycleTLS#206]
### could you make a discord server, it would be much better for question asking and whatnot

**Comment by Danny-Dasilva** [comment]
> is this project abandoned? why no issue get's answered

It's the holidays, I'm working on a release but it needs additional tests. A lot of these issues are duplicates of previous ones that are known.

**Comment by Danny-Dasilva** [comment]
I will setup a discord community and add it to the readme sometime within the week.

**Comment by Danny-Dasilva** [comment]
I added a discord community to the project homepage, feel free to join [1.0.22](https://github.com/Danny-Dasilva/CycleTLS/pull/266)

https://discord.gg/gsmxMHrwhu
