### ISSUE TITLE
POST 408

### ISSUE THREAD

**Issue by qizhoumeng** [Danny-Dasilva/CycleTLS#215]
### Description

Hello. When I use post request and the body passes parameters, it always returns 408. How can I solve this problem

### Node Version

None

### Golang Version

None

### Relevant Log Output

```shell
Request returned a Syscall Error: Post "url": net/http: request canceled (Client.Timeout exceeded while awaiting headers)->
```

**Comment by snekROmonoro** [comment]
sometimes I seem to also have this issue ^^

**Comment by pyzzd** [comment]
解决了吗，我是这个问题
