### ISSUE TITLE
[HELP] Golang Cookies Temporary workaround

### ISSUE THREAD

**Issue by killcod3** [Danny-Dasilva/CycleTLS#222]
### Description

Ok so i made a temporary word around to parse SET Cookie header programmatically, where set_cook is typical sert cookie header

```
var array []*cycletls.Cookie
	set_cook := `guest=7312507968414977526; Domain=xyz.com; Path=/; Expires=Wed, 03 Jan 2024 21:56:48 GMT/,/siftsession=4322192087546535703; Domain=xyz.com; Path=/; Expires=Thu, 05 Jan 2023 02:56:48 GMT; Secure/,/override_session=0; Domain=xyz.com; Path=/; Expires=Thu, 04 Jan 2024 02:56:48 GMT; HttpOnly/,/siftsession=2500875263203479269; Domain=xyz.com; Path=/; Expires=Thu, 05 Jan 2023 02:56:48 GMT; Secure/,/secure_login=1; Domain=xyz.com; Path=/; Expires=Thu, 04 Jan 2024 02:56:49 GMT; HttpOnly; Secure/,/secure_check=1; Domain=xyz.com; Path=/; Expires=Thu, 04 Jan 2024 02:56:49 GMT; HttpOnly; Secure/,/session=13779298769476582329%3A7959720342228217944; Domain=xyz.com; Path=/; Expires=Thu, 04 Jan 2024 02:56:49 GMT; HttpOnly; Secure; SameSite=Lax/,/guest=; Domain=xyz.com; Path=/; Expires=Tue, 03 Jan 2023 02:56:49 GMT; HttpOnly/,/okc_locale=en; Domain=xyz.com; Path=/; Secure; SameSite=Strict`
	data1 := strings.Split(set_cook, "/,/")
	for _, element := range data1 {
		r := regexp.MustCompile(`^\s*(.*?)\s*;`)
		match := r.FindString(element)
		rawcook := strings.Replace(match, ";", "", 1)
		r1 := regexp.MustCompile(`=$`)
		if !(r1.MatchString(rawcook)) {
			//fmt.Print(rawcook + "\n")
			data2 := strings.Split(rawcook, "=")
			tmp := &cycletls.Cookie{}
			tmp.Name = data2[0]
			tmp.Value = data2[1]

			array = append(array, tmp)

		}

	}
	//fmt.Print(array)
	b, err := json.Marshal(&array)

	if err != nil {
		log.Println(err)

	}
	fmt.Print(string(b))
```
this can generate a json object but the problem is how to pass it to the cookies option?

### Issue Type

Support

### Operating System

windows/amd64

### Node Version

None

### Golang Version

1.19.4

### Relevant Log Output

`[{"name":"guest","value":"7312507968414977526","path":"","domain":"","Expires":"0001-01-01T00:00:00Z","expires":"0001-01-01T00:00:00Z","rawExpires":"","maxAge":0,"secure":false,"httpOnly":false,"sameSite":0,"Raw":"","unparsed":null},{"name":"siftsession","value":"4322192087546535703","path":"","domain":"","Expires":"0001-01-01T00:00:00Z","expires":"0001-01-01T00:00:00Z","rawExpires":"","maxAge":0,"secure":false,"httpOnly":false,"sameSite":0,"Raw":"","unparsed":null},{"name":"override_session","value":"0","path":"","domain":"","Expires":"0001-01-01T00:00:00Z","expires":"0001-01-01T00:00:00Z","rawExpires":"","maxAge":0,"secure":false,"httpOnly":false,"sameSite":0,"Raw":"","unparsed":null},{"name":"siftsession","value":"2500875263203479269","path":"","domain":"","Expires":"0001-01-01T00:00:00Z","expires":"0001-01-01T00:00:00Z","rawExpires":"","maxAge":0,"secure":false,"httpOnly":false,"sameSite":0,"Raw":"","unparsed":null},{"name":"secure_login","value":"1","path":"","domain":"","Expires":"0001-01-01T00:00:00Z","expires":"0001-01-01T00:00:00Z","rawExpires":"","maxAge":0,"secure":false,"httpOnly":false,"sameSite":0,"Raw":"","unparsed":null},{"name":"secure_check","value":"1","path":"","domain":"","Expires":"0001-01-01T00:00:00Z","expires":"0001-01-01T00:00:00Z","rawExpires":"","maxAge":0,"secure":false,"httpOnly":false,"sameSite":0,"Raw":"","unparsed":null},{"name":"session","value":"13779298769476582329%3A7959720342228217944","path":"","domain":"","Expires":"0001-01-01T00:00:00Z","expires":"0001-01-01T00:00:00Z","rawExpires":"","maxAge":0,"secure":false,"httpOnly":false,"sameSite":0,"Raw":"","unparsed":null},{"name":"okc_locale","value":"en","path":"","domain":"","Expires":"0001-01-01T00:00:00Z","expires":"0001-01-01T00:00:00Z","rawExpires":"","maxAge":0,"secure":false,"httpOnly":false,"sameSite":0,"Raw":"","unparsed":null}]`

**Comment by Danny-Dasilva** [comment]
Support has been added for cookiejar and the docs in the ReadMe have been updated on the latest release
https://github.com/Danny-Dasilva/CycleTLS#how-do-i-use-cookiejar-in-cycletls


```go
package main

import (
	"github.com/Danny-Dasilva/CycleTLS/cycletls"
	"log"
	"net/http/cookiejar"
	"net/url"
	"strings"
)
func main() {
	client := cycletls.Init()
	jar, err := cookiejar.New(nil)
        if err != nil {
            log.Fatal(err)
        }
	// First request to set cookie
	firstResponse, err := client.Do("https://httpbin.org/cookies/set?a=1&b=2&c=3", cycletls.Options{
		Body: "",
		  Ja3:       "771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,0-23-65281-10-11-35-16-5-13-18-51-45-43-27-17513,29-23-24,0",
		  UserAgent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36",
		  DisableRedirect: true,
	  },
		 "GET")
	if err != nil {
		log.Fatal(err)
	}
	firstURL, _ := url.Parse(firstResponse.FinalUrl)
        jar.SetCookies( firstURL, firstResponse.Cookies)


	// Second request to verify cookies, including the cookies from the first response
	secondResponse, err := client.Do("https://httpbin.org/cookies", cycletls.Options{
    Body: "",
    Ja3:       "771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,0-23-65281-10-11-35-16-5-13-18-51-45-43-27-17513,29-23-24,0",
    UserAgent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36",
    Headers: map[string]string{
        "Cookie": getHeadersFromJar(jar, firstURL),
    },
	}, "GET")
	if err != nil {
	    log.Fatal(err)
	}

	log.Println("Second Response body:", secondResponse.Body)
}


func getHeadersFromJar(jar *cookiejar.Jar, url *url.URL) string {
    cookies := jar.Cookies(url)
    var cookieStrs []string
    for _, cookie := range cookies {
        cookieStrs = append(cookieStrs, cookie.Name+"="+cookie.Value)
    }
    return strings.Join(cookieStrs, "; ")
}
```
