### ISSUE TITLE
Consider tagging submodule "cycletls"?

### ISSUE THREAD

**Issue by Rick-xuy** [Danny-Dasilva/CycleTLS#232]
### Description

I found that package `github.com/Danny-Dasilva/CycleTLS/cycletls` is placed in submodule `github.com/Danny-Dasilva/CycleTLS/cycletls`. <br>
However, it seems that submodule `github.com/Danny-Dasilva/CycleTLS/cycletls` is not tagged. According to [Go Modules wiki](https://github.com/golang/go/wiki/Modules#is-it-possible-to-add-a-module-to-a-multi-module-repository), submodule should be tagged like `relative-path-to-root/vX.X.X`.
At now, when trying to import package `github.com/Danny-Dasilva/CycleTLS/cycletls`, downstream would depends on **pseudo-version** of module `github.com/Danny-Dasilva/CycleTLS/cycletls`.
```
github.com/Danny-Dasilva/CycleTLS/cycletls v0.0.0-20220620102923-c84d740b4757
```
I think it is not very readable and difficult to upgrade. This is not conductive to version control either.
So, I propose whether it is possible to tag submodule properly. For example, `cycletls/v0.0.1`, `cycletls/v1.0.0`etc, so that other project can use tag to import this module in go.mod.

### Issue Type

Support

### Operating System

Windows 10

### Node Version

None

### Golang Version

Go 17.x

**Comment by Danny-Dasilva** [comment]
I'll get this setup for the next release

**Comment by Danny-Dasilva** [comment]
submodules should now be tagged with [the latest release](https://github.com/Danny-Dasilva/CycleTLS/pull/284), make take a while to propagate but this should work

```
//go.mod

require github.com/Danny-Dasilva/CycleTLS/cycletls v1.0.23

```
