### ISSUE TITLE
What cycletls.WSEndpoint handler does and how to use it?

### ISSUE THREAD

**Issue by zxc95** [Danny-Dasilva/CycleTLS#244]
### Description

Could you please explain what cycletls.WSEndpoint handler does and how to use it?

### Issue Type

Documentation Request

### Node Version

None

### Golang Version

None

**Comment by Danny-Dasilva** [comment]
it's used to spawn the websocket server that the client/nodejs side connects to in order to send requests. If you're a golang developer it doesn't provide much use.
