### ISSUE TITLE
stream error: stream ID 15; PROTOCOL\_ERROR; server not authoritative for push with host XXX

### ISSUE THREAD

**Issue by rakoo** [Danny-Dasilva/CycleTLS#246]
### Description

Hey there ! Thanks for your project :)

I'm using it through https://github.com/mrusme/journalist which in turns is used in https://github.com/mrusme/reader, and I'm having an issue with the following url:

https://basta.media/la-ligue-des-droits-de-l-homme-appelle-au-combat-pour-les-libertes-et-la-democratie-Darmanin-subventions

Here's a little reproducer:
```
package main

import (
	"fmt"
	"log"

	"github.com/Danny-Dasilva/CycleTLS/cycletls"
)

func main() {
	client := cycletls.Init()

	r, err := client.Do("https://basta.media/la-ligue-des-droits-de-l-homme-appelle-au-combat-pour-les-libertes-et-la-democratie-Darmanin-subventions", cycletls.Options{
		Body:      "",
		Ja3:       "771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-51-57-47-53-10,0-23-65281-10-11-35-16-5-51-43-13-45-28-21,29-23-24-25-256-257,0",
		UserAgent: "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0",
	}, "GET")
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(r.Body)
}
```

`err` is `nil`, but the body is an error:

```
->
Get "https://basta.media/la-ligue-des-droits-de-l-homme-appelle-au-combat-pour-les-libertes-et-la-democratie-Darmanin-subventions": stream error: stream ID 15; PROTOCOL_ERROR; server not authoritative for push with host "basta.media"
```

It's probably a config issue on the server side, but is it possible from the client to try http/2 and then fallback to http/1.1 if the first one fails ? It sounds like an issue with http/2 specifically

### Issue Type

Bug

### Operating System

Linux

### Node Version

None

### Golang Version

1.20.2

**Comment by 4cq2** [comment]
why do you even need JA3 with this? a normal cURL request seems to work, so `net/http` should work as well.

**Comment by rakoo** [comment]
I don't know if I need ja3, I'm just using this as a lib so I don't have a way to easily change that
