### ISSUE TITLE
41：pre_shared_key  not working

### ISSUE THREAD

**Issue by yuzd** [Danny-Dasilva/CycleTLS#249]
### Description

``` js
771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,17513-10-18-11-51-13-27-0-35-65281-43-16-45-5-23-21-41,29-23-24,0
```
``` go
"41": &utls.GenericExtension{Id: 41},
```

uTlsConn.Handshake() error: remote error: tls: unexpected message

### Issue Type

Bug, Feature Request

### Operating System

Windows 10, Linux, Mac OS

### Node Version

None

### Golang Version

Go 17.x

**Comment by yuzd** [comment]
用最新版本的utls

**Comment by wangluozhe** [comment]
我用的就是最新版本的utls，但是他还是会解密不了数据，我能不能加你一个联系方式啊！
