### ISSUE TITLE
Missing Gif/Avif/... support in Decoding

### ISSUE THREAD

**Issue by benjiro29** [Danny-Dasilva/CycleTLS#262]
### Description

There is a missing decoding types in utils.go, line 62:

	decodingTypes := map[string]bool{
			"image/svg+xml":   true,
			"image/webp":      true,
			"image/jpeg":      true,
			"image/png":       true,
			"image/gif":       true, // Added
			"image/avif":       true, // Added
			"application/pdf": true,
		}

Currently gif, avif etc are all missing. This will result in jpeg being base64, while non-support being pure string.

### Issue Type

Bug

### Operating System

Linux

### Node Version

None

### Golang Version

Go 17.x

**Comment by Danny-Dasilva** [comment]
this should now be supported in version [1.0.22](https://github.com/Danny-Dasilva/CycleTLS/pull/266)
