### ISSUE TITLE
is there a way to support socks5 proxy?

### ISSUE THREAD

**Issue by jianmaikj** [Danny-Dasilva/CycleTLS#263]
### Description

I got this error: `scheme socks5 is not supported` when i were using socks5 proxy.
Thanks for help

### Issue Type

Feature Request

### Operating System

Windows 10

### Node Version

Node 16.x

### Golang Version

Other

**Comment by Danny-Dasilva** [comment]
this should now be supported in version [1.0.22](https://github.com/Danny-Dasilva/CycleTLS/pull/266)
