### ISSUE TITLE
There are lot's of memory leaks, DDoS and infinite loop if any error in NodeJS

### ISSUE THREAD

**Issue by vikasg603** [Danny-Dasilva/CycleTLS#264]
### Description

Hey team, First of all, thanks for the work, This library is helping me and my organization. 
Below are some very important issues I wanted to raise in terms of the npm package.

**The library fails when we have packaged application**
When building a single JS packaged file using any packing tools like WebPack, or Electron-Builder, The current version will fail and go into an infinite loop as the executable is not available, and the initCycleTLS is continuously retrying it.
In the current version, there is no way to pass the CycleTLS golang executable path as the config and no way to solve this problem without making changes inside the node_modules (Which is not suitable, since editing node_modules directly is never a solution)

**The library will go into an infinite loop if any error while starting the WebSocket Connection** 
I see in the current version of the library, that if port number 9119 is occupied by some other process or the golang binary fails to start due to any reason, The program will go into an infinite loop and will never resolve the initCycleTLS promise which can interrupt other services.

**If other services killed the socket process running on 9119, The attacker can attack the process with DDoS.**
For this, there are 2 places from where the possible DDoS can happen
1. On any requests sent in the past, Promise will never resolve and will use the memory for no reason.
2. On any new requests coming, I see the script is adding the requests in the queue and then keeps trying them every 0.1 seconds, This can either throw an unhandled error since this.server.send will fail as websocket is closed or will just keep on increasing the queue and memory.

### Issue Type

Bug, Performance

### Operating System

Windows 10, Linux, Mac OS

### Node Version

Node 16.x

### Golang Version

Go 17.x

**Comment by Danny-Dasilva** [comment]
this should now be addressed in version [1.0.22](https://github.com/Danny-Dasilva/CycleTLS/pull/266). Multiple nodejs and golang fixes were done so if this persists feel free to re-open this issue. The downside of the specific implementation is that requests get lost if the binary has downtime. I should have a fix for that eventually as well.

**Comment by hadoan** [comment]
Hey folks — ran into a similar memory issue recently.

I’m working on a free tool that helps analyze heap snapshots (Node, Python, .NET, etc.) and spot leaks like this one.

Just wanted to share in case it’s helpful for others debugging similar problems.

Happy to chat or give early access if anyone’s interested!
