### ISSUE TITLE
[?] How can i specify HTTP version

### ISSUE THREAD

**Issue by morrphology** [Danny-Dasilva/CycleTLS#268]
### Description

[?] How can i specify HTTP version

### Issue Type

Support

### Node Version

Node 16.x

### Golang Version

None

**Comment by Danny-Dasilva** [comment]
It gets automatically set depending on the Ja3 you pass in, I can add the option to make this configurable but it will change the expected ja3

**Comment by morrphology** [comment]
> It gets automatically set depending on the Ja3 you pass in, I can add the option to make this configurable but it will change the expected ja3

so there is no way to set it to HTTP/1.1 rn? i generated a random ja3 in each request

**Comment by Danny-Dasilva** [comment]
This feature has been added to [version 1.0.23](https://github.com/Danny-Dasilva/CycleTLS/pull/284)

Examples have been added in the docs but for clarity here's some code examples

golang
https://github.com/Danny-Dasilva/CycleTLS/blob/000594cc8ecbff4df1a604b724c52558e5091a62/cycletls/tests/integration/ForceHTTP1_test.go#L43-L65

javascript
https://github.com/Danny-Dasilva/CycleTLS/blob/f6c898f1bb298f3d6dd7fcfdfb531d950cc587a3/tests/forceHTTP1.test.ts#L34-L47
