### ISSUE TITLE
无法访问dex类型的数据

### ISSUE THREAD

**Issue by supermigo** [Danny-Dasilva/CycleTLS#276]
### Description

https://www.dextools.io/shared/data/pair?address=0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640&chain=ether&audit=false&locks=true
respone：
uTlsConn.Handshake() error: remote error: tls: error decoding message", Headers:map[string]string{}}

### Node Version

None

### Golang Version

None

**Comment by supermigo** [comment]
Issue Type
uTlsConn.Handshake() error: remote error: tls: error decoding message", Headers:map[string]string{}}



Operating System
mac osx 

Node Version
None

Golang Version
1.21

Relevant Log Output
No response

**Comment by Danny-Dasilva** [comment]
> Issue Type uTlsConn.Handshake() error: remote error: tls: error decoding message", Headers:map[string]string{}}
> 
> Operating System mac osx
> 
> Node Version None
> 
> Golang Version 1.21
> 
> Relevant Log Output No response

can you send me the request you are sending, I think there's some issue with the included headers but it's hard to reproduce this issue without seeing what request is being made

**Comment by supermigo** [comment]
Code.:
`cc := cycletls.Init()
	//https://app.geckoterminal.com/api/p1/candlesticks/161750316/197940?resolution=15&from_timestamp=1700245800&to_timestamp=1700271000&for_update=false&count_back=28&currency=usd&is_inverted=false
	//https://www.dextools.io/shared/data/pair?address=0xbabfb8eac3d264e5e55a22f7bd83e73aa3227e9f&chain=bsc&audit=true&locks=true
	resoibsem, err := cc.Do("https://www.dextools.io/shared/data/pair?address=0xbabfb8eac3d264e5e55a22f7bd83e73aa3227e9f&chain=bsc&audit=true&locks=true", cycletls.Options{
		Body:      "",
		Ja3:       "771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-51-57-47-53-10,0-23-65281-10-11-35-16-5-51-43-13-45-28-21,29-23-24-25-256-257,0",
		UserAgent: "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0",
	}, "GET")
	if err != nil {
		fmt.Println(err.Error())
	} else {
		fmt.Printf("%#+v", resoibsem)
	}

two url for test.
the first url use this ja3 is right;
but when use dextools.io  will get the uTlsConn.Handshake() error: remote error: tls: error decoding message", Headers:map[string]string{}} msg;
where can i  get the ja3 value.

**Comment by Danny-Dasilva** [comment]
This should be addressed/fixed
```
func main() {

	cc := cycletls.Init()
	//https://app.geckoterminal.com/api/p1/candlesticks/161750316/197940?resolution=15&from_timestamp=1700245800&to_timestamp=1700271000&for_update=false&count_back=28&currency=usd&is_inverted=false
	//https://www.dextools.io/shared/data/pair?address=0xbabfb8eac3d264e5e55a22f7bd83e73aa3227e9f&chain=bsc&audit=true&locks=true
	response, _ := cc.Do("https://www.dextools.io/shared/data/pair?address=0xbabfb8eac3d264e5e55a22f7bd83e73aa3227e9f&chain=bsc&audit=true&locks=true", cycletls.Options{
		Body:      "",
		Ja3:       "771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-51-57-47-53-10,0-23-65281-10-11-35-16-5-51-43-13-45-28-21,29-23-24-25-256-257,0",
		UserAgent: "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0",
	}, "GET")
	log.Println(response.Body)

	response2, _ := cc.Do("https://app.geckoterminal.com/api/p1/candlesticks/161750316/197940?resolution=15&from_timestamp=1700245800&to_timestamp=1700271000&for_update=false&count_back=28&currency=usd&is_inverted=false", cycletls.Options{
		Body:      "",
		Ja3:       "771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-51-57-47-53-10,0-23-65281-10-11-35-16-5-51-43-13-45-28-21,29-23-24-25-256-257,0",
		UserAgent: "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0",
	}, "GET")
	log.Println(response2.Body)

}

```

neither response raises a handshake error on the latest release

feel free to run `go get -u github.com/Danny-Dasilva/CycleTLS/cycletls` and test for yourself.

If you encounter the error still feel free to reopen this issue
