### ISSUE TITLE
Import Error: github.com/refraction-networking/utls ⇒ github.com/Danny-Dasilva/utls in Danny-Dasilva/fhttp?

### ISSUE THREAD

**Issue by deoxykev** [Danny-Dasilva/CycleTLS#287]
### Description

I'm getting this error when I import `github.com/Danny-Dasilva/fhttp`

```
github.com/Danny-Dasilva/CycleTLS/cycletls
/Users/k/go/pkg/mod/github.com/!danny-!dasilva/!cycle!t!l!s/cycletls@v0.0.0-20231128002513-4df48e6bd744/roundtripper.go:138:34: cannot use rt.dialTLSHTTP2 (value of type func(network string, addr string, _ *"github.com/Danny-Dasilva/utls".Config) (net.Conn, error)) as func(network string, addr string, cfg *"github.com/refraction-networking/utls".Config) (net.Conn, error) value in struct literal
```
---

I think there is an issue with https://github.com/Danny-Dasilva/fhttp/blob/9494939f30fadcc0724f320f1aff62bdcc73f01e/http2/http2.go#L29
using `github.com/refraction-networking/utls` instead of `github.com/Danny-Dasilva/utls`

I'm not 100% sure though, can you take a look?

### Issue Type

Bug

### Operating System

Mac OS

### Node Version

None

### Golang Version

Go 17.x

### Relevant Log Output

```shell
github.com/Danny-Dasilva/CycleTLS/cycletls
/Users/k/go/pkg/mod/github.com/!danny-!dasilva/!cycle!t!l!s/cycletls@v0.0.0-20231128002513-4df48e6bd744/roundtripper.go:138:34: cannot use rt.dialTLSHTTP2 (value of type func(network string, addr string, _ *"github.com/Danny-Dasilva/utls".Config) (net.Conn, error)) as func(network string, addr string, cfg *"github.com/refraction-networking/utls".Config) (net.Conn, error) value in struct literal
```

**Comment by Danny-Dasilva** [comment]
This should be fixed shortly, the latest CycleTLS release will go back to using the original `github.com/refraction-networking/utls`. This should be fixed as soon as [this PR](https://github.com/Danny-Dasilva/CycleTLS/pull/284) is pushed

**Comment by Danny-Dasilva** [comment]
This should be fixed 

`go get -u github.com/Danny-Dasilva/CycleTLS/cycletls` should resolve this issue

feel free to re-open if you experience it again. The new modules don't reference `github.com/Danny-Dasilva/utls` anymore
