### ISSUE TITLE
Golang cmd window not hiding

### ISSUE THREAD

**Issue by roachadam** [Danny-Dasilva/CycleTLS#30]
**Actual behavior** 
Golang cmd window opens and remains visible until exit.

**Expected behavior** 
Golang cmd window is never visible.

**To Reproduce** Steps to reproduce the behavior

1.  Run example code

**Additional Information**

-   Operating System information: 
Windows 10 Pro
Version	20H2
OS build	19042.1052

-   Node version: v14.17.2
-   Golang version: ?

![image](https://user-images.githubusercontent.com/30098945/124403272-245e6480-dcfb-11eb-9b58-ec21649a7f47.png)

Proposed solution:
- Remove 'detached' spawn argument. Seems to be a known node issue: 
- https://github.com/nodejs/node/issues/21825 
- https://github.com/nodejs/node/issues/15217#issuecomment-331860528

**Comment by Danny-Dasilva** [comment]
spawned window should be hidden on windows in [this pr](https://github.com/Danny-Dasilva/CycleTLS/pull/38) and included in version 0.0.12
