### ISSUE TITLE
Socks5h support

### ISSUE THREAD

**Issue by Loclhost** [Danny-Dasilva/CycleTLS#301]
### Description

How can i set up Socks5h proxy?

### Issue Type

Others

### Operating System

Windows 10

### Node Version

Node 16.x

### Golang Version

Go 17.x

**Comment by Danny-Dasilva** [comment]
something like this should work, let me know if it doesn't
https://github.com/Danny-Dasilva/CycleTLS/blob/a120dacc1abdac2b96529ad61c155210e538674b/cycletls/tests/integration/proxy_test.go#L14-L37

**Comment by Danny-Dasilva** [comment]
closing this as it's now supported on the latest release
