### ISSUE TITLE
 uTlsConn.Handshake() error: remote error: tls: handshake failure 

### ISSUE THREAD

**Issue by NewStartMe** [Danny-Dasilva/CycleTLS#315]
### Description

(async () => {
    // Initiate CycleTLS
    const cycleTLS = await initCycleTLS();

    // Send request
    const response = await cycleTLS('https://xxx', {
        body: 'xxx',
        ja3: ja3,
        userAgent: userAgent,
        headers: headers,
        cookies: cookies
        // proxy: 'http://username:password@hostname.com:443'
    }, 'post');

    console.log('status:', response.status, 'success:', response.body);
    // Cleanly exit CycleTLS
    cycleTLS.exit();
})();
i used in this way,but got error about.[ status: 0 success: ->uTlsConn.Handshake() error: remote error: tls: handshake failure
 ]

### Issue Type

Others

### Operating System

Mac OS

### Node Version

Other

### Golang Version

Other

**Comment by lif0** [comment]
perhaps send an incorrect ja3, which is why the remote service responds to you with an error

**Comment by lif0** [comment]
if you send me the ja3 you are spoof, maybe I can help you.

**Comment by NewStartMe** [comment]
> if you send me the ja3 you are spoof, maybe I can help you.

You're right. Problem solved. Thank you very much！
