### ISSUE TITLE
did u add support for HTTP 1.1 yet?

### ISSUE THREAD

**Issue by Were-Logan-0110** [Danny-Dasilva/CycleTLS#321]
### Description

did u add support for HTTP 1.1 yet?

### Issue Type

Support

### Node Version

None

### Golang Version

None

**Comment by Danny-Dasilva** [comment]
support documentation is here 
https://github.com/Danny-Dasilva/CycleTLS?tab=readme-ov-file#how-do-i-setforce-http1
<img width="803" alt="image" src="https://github.com/user-attachments/assets/b2d3c85f-d1aa-4549-9c42-ad1dfb1e5a66">
