### ISSUE TITLE
CRASH WITH JA3!

### ISSUE THREAD

**Issue by nop4LOL** [Danny-Dasilva/CycleTLS#322]
### Description

IF OPTIONS.JA3 IS "" OR DONT GIVE JA3 PARAM , CLIENT.DO() WILL CRASH !!!!

`goroutine 1 [running]:                                                          
github.com/Danny-Dasilva/CycleTLS/cycletls.StringToSpec({0x0, 0x0}, {0x11c8495, 
0x4c}, 0x0)                                                                     
        F:/Program Files/Goproject/pkg/mod/github.com/!danny-!dasilva/!cycle!t!l
!s/cycletls@v1.0.25/utils.go:116 +0x1157                                        
github.com/Danny-Dasilva/CycleTLS/cycletls.(*roundTripper).dialTLS(0xa85c100, {0
x1239988, 0xa85e500}, {0x11b17dc, 0x3}, {0xa80a9b0, 0xc})                       
        F:/Program Files/Goproject/pkg/mod/github.com/!danny-!dasilva/!cycle!t!l
!s/cycletls@v1.0.25/roundtripper.go:105 +0x1d7                                  
github.com/Danny-Dasilva/CycleTLS/cycletls.(*roundTripper).getTransport(0xa85c10
0, 0xa8767e0, {0xa80a9b0, 0xc})                                                 
        F:/Program Files/Goproject/pkg/mod/github.com/!danny-!dasilva/!cycle!t!l
!s/cycletls@v1.0.25/roundtripper.go:72 +0x1b1                                   
github.com/Danny-Dasilva/CycleTLS/cycletls.(*roundTripper).RoundTrip(0xa85c100, 
0xa8767e0)                                                                      
`

**I DONT WANT EVERY REQUEST MUST APPOINT A JA3 STRING , CAN YOU PLEASE LET CYCLETLS PKG CAN SEND NORMAL HTTP REQUEST WITH DEFAULT TLS JA3 ?

JUST LIKE THIS CAN WORK IS OK ( In this latest version will CRASH ) :**

`http.Do("https://google.com", cycletls.Options{}, "GET")`

### Issue Type

Bug

### Operating System

Windows 10

### Node Version

Other

### Golang Version

Other

**Comment by lif0** [comment]
Thank you🫵✨
Maybe I can fix it, I'll return the error instead of panicking, is that okay?

**Comment by Danny-Dasilva** [comment]
I've defaulted values in case they're not passed in the latest 1.0.26 release
