### ISSUE TITLE
Method in CycleTLS.Do isn't used

### ISSUE THREAD

**Issue by LeBatou** [Danny-Dasilva/CycleTLS#33]
When you add the method in the Do paramaters it doesn't work but if you add it in the CycleTLS.option(), it works

When you add the method in the Do paramaters it should take the method and not add GET by default

client := cycletls.Init()
request, err := client.Do(urlString, options, "POST");

![image](https://user-images.githubusercontent.com/47107713/127389396-2b2b6db3-8061-4a6b-9aa8-70c16bc8e2fe.png)
As you can see in this photo, Method is never used in the "Do" function

**Comment by Danny-Dasilva** [comment]
Addressed by [this pr](https://github.com/Danny-Dasilva/CycleTLS/pull/38)
