### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by Mobeen22-creator** [Danny-Dasilva/CycleTLS#34]
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::9119
←[90m    at Server.setupListenHandle [as _listen2] (net.js:1318:16)←[39m
←[90m    at listenInCluster (net.js:1366:12)←[39m
←[90m    at Server.listen (net.js:1452:7)←[39m
    at new WebSocketServer (C:\Users\Mobeen\node_modules\←[4mws←[24m\lib\websocket-server.js:75:20)
    at new Golang (C:\Users\Mobeen\node_modules\←[4mcycletls←[24m\dist\index.js:39:23)
    at C:\Users\Mobeen\node_modules\←[4mcycletls←[24m\dist\index.js:94:26
    at new Promise (<anonymous>)
    at initCycleTLS (C:\Users\Mobeen\node_modules\←[4mcycletls←[24m\dist\index.js:88:12)
    at setEmail (C:\Users\Mobeen\Downloads\cheetahv20-main\mesh.js:68:26)
    at atcTLS (C:\Users\Mobeen\Downloads\cheetahv20-main\mesh.js:62:7)
Emitted 'error' event on WebSocketServer instance at:
←[90m    at Server.emit (events.js:315:20)←[39m
←[90m    at emitErrorNT (net.js:1345:8)←[39m
←[90m    at processTicksAndRejections (internal/process/task_queues.js:80:21)←[39m {
  code: ←[32m'EADDRINUSE'←[39m,
  errno: ←[33m-4091←[39m,
  syscall: ←[32m'listen'←[39m,
  address: ←[32m'::'←[39m,
  port: ←[33m9119←[39m
}

Getting this error. I think its due to port issue.

**Comment by Danny-Dasilva** [comment]
This is a multi instance issue, CycleTLS uses a websiclet port to communicate to the golang side. You can assign a port in the unit function


`const cycleTLS = await initCycleTLS({port: 9117});`

Use different ports for different instances. 

I will have multiple instance support in an upcoming PR soon.

**Comment by Mobeen22-creator** [comment]
> This is a multi instance issue, CycleTLS uses a websocket port to communicate to the golang side. You can assign a port in the init function
> 
> `const cycleTLS = await initCycleTLS({port: 9117});`
> 
> Use different ports for different instances.
> 
> I will have multiple instance support in an upcoming PR soon.

thanks. Its worked!!
