### ISSUE TITLE
Path error when compiling

### ISSUE THREAD

**Issue by marwanabaris** [Danny-Dasilva/CycleTLS#35]
I've compiled my script which uses CycleTLS - it works fine when running  in my IDE however after compiling using PKG, I get an error which I've attached an image of. 
![image](https://user-images.githubusercontent.com/72098360/128038118-c42c5e0e-ecfe-49b9-8021-d55eb2d6e650.png)

**Comment by Danny-Dasilva** [comment]
Excuse me for my ignorance but is this being run inside PowerShell?

**Comment by marwanabaris** [comment]
> Excuse me for my ignorance but is this being run inside PowerShell?

I'm running my exe via Powershell to capture the error, it's definately a PKG executable.

**Comment by Danny-Dasilva** [comment]
Right so CycleTLS spawns a golang process which is killed when it clean exists. That error you are seeing is a windows cmd command trying to kill the spawned golang process.

I can look into integrating a PowerShell specific task kill so this issue doesn't appear. 

For now if you run your PKG file in a CMD window and not PowerShell it should work.

**Comment by marwanabaris** [comment]
> Right so CycleTLS spawns a golang process which is killed when it clean exists. That error you are seeing is a windows cmd command trying to kill the spawned golang process (Since it's PowerShell its erroring out because I don't have a way to catch spawned PowerShell processes).
> 
> I can look into integrating a PowerShell specific task kill so this issue doesn't appear.
> 
> For now if you run your PKG file in a CMD window and not PowerShell one it should work.

Hm, I'm only running it in Powershell because I've set my exe to close when faced with an error, I've changed that so that I could print the error on the CLI and it shows the same error. I've also tried on CMD, the error persists. It's quite odd because if I can the uncompiled script via CMD or my IDE everything is good.
