### ISSUE TITLE
403 issue in deployment (server ubuntu)

### ISSUE THREAD

**Issue by iarsham** [Danny-Dasilva/CycleTLS#354]
### Description

my app using cycletls package and works fine in local
today I deploy my app to server and get 403 from targets!!

what is wrong what I should to in deploy mode?

### Issue Type

Feature Request

### Operating System

Linux

### Node Version

None

### Golang Version

Go 17.x

### Relevant Log Output
![image](https://github.com/user-attachments/assets/873d9086-dccf-45f2-9cb1-d80b9e635f9b)

_No response_

**Comment by Danny-Dasilva** [comment]
this is likely related to the server IP, my recommendations would be to rotate through proxies or use a different ubuntu server. Often Google/Akamai/Cloudflare keep a list of datacenter servers that they blacklist at the ip address level.
