### ISSUE TITLE
Decompress a (gzip/br/etc) compressed response body before returning it

### ISSUE THREAD

**Issue by frzsombor** [Danny-Dasilva/CycleTLS#48]
*Requested feature*
If the request results in a compressed response, decompress the data before setting the value to `response.body`

*Why the feature is needed*
If we are sending a request with `Accept-Encoding` in the headers (for example: `'Accept-Encoding': 'gzip, deflate, br'`) and the server responds with a compressed (for example gzipped) response, `response.body` will store this compressed "non-processable" raw data (which also possibly gets corrupted somehow, but this is just an assumption based on the fact I failed to decompress it on the first few tries with `zlib.gunzipSync` _[Error: incorrect header check]_). I tried to fix this and send a PR, but I'm afraid this has to be fixed on the Go side, which is unfortunately out of my knowledge.

**Comment by Danny-Dasilva** [comment]
Implemented in [0.0.15](https://github.com/Danny-Dasilva/CycleTLS/pull/59). Gzip/deflate/broli should now be decoded on the Golang side.
