### ISSUE TITLE
Reusing connection and MaxIdleConnsPerHost option add

### ISSUE THREAD

**Issue by rezoners** [Danny-Dasilva/CycleTLS#49]
Hello, as i understand every request CycleTls makes a new connection.
Is there any possible to create someting like ordinary http client with some options like ja3 and headers and reuse connection instead of creating new one every time.

right now i'm using something like this

tr, err := NewTransport(ja3sting)
tr.MaxIdleConnsPerHost = 50
httpClient = &http.Client{Transport: tr, Timeout: 10 * time.Second}

**Comment by Danny-Dasilva** [comment]
Yes, CycleTLS uses a custom httpClient so this is doable, I can cache the transport and reuse it on following requests (this is already done on the main handshake). On the ts/js side it will probably look something like this. 

```js


const response = await cycleTLS.get('https://ja3er.com/json', {
    ja3: '771,49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53-10,65281-0-23-35-13-5-18-16-11-10,29-23-24,0',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3165.0 Safari/537.36',
  }, cache=true);
```
Let me know if you have any API recommendations/preferences.

**Comment by rezoners** [comment]
Thanks for answer i will look into it.

**Comment by Keira-Shuyao** [comment]
Hi @Danny-Dasilva ,is reusing connection already implemented? I didn't see the `cache` API on the npm package.
My usecase involves sending requests to one host via proxy frequently, right now the lantency is about 3 times to the same request in http2 in Node.
