### ISSUE TITLE
Do not exit the whole process on error/crash but reinitialise CycleTLS

### ISSUE THREAD

**Issue by frzsombor** [Danny-Dasilva/CycleTLS#50]
*Requested feature*
I think there should be a user configurable option (like 'restartOnCrash' or similar), that is checked in `cleanExit`, and after killing the child process by pid, skips the `process.exit();` lines, and instead, calls a function, that closes the ws server (important, to be able to use the port again) and runs and waits for `initCycleTLS` again, so an unexpected error in the Go parts wont result in closing down the whole application using this library - but re-spawns a working child.

*Why the feature is needed*
Errors can happen anytime. 

*Proposed solution*
I think the best solution would be that after an unexpected error/crash, if a specified option is set (or either by default), the invoked `await cycleTLS(url, ...` would only resolve (or reject) if
 - the error is handled (logged)
 - the child process is killed
 - the ws server is closed
 - the `initCycleTLS` is re-called and resolved as ready

This way, when someone calls cycleTLS(...) with await, no matter if it failed - even with a crash - it won't break the workflow of the main application (or exit) and someone can expect an "always available" submodule that they can call again, anytime.

**Comment by Danny-Dasilva** [comment]
Implemented in [0.0.15](https://github.com/Danny-Dasilva/CycleTLS/pull/59). Requests sent when the process crashes are cached in local memory and sent as soon as the process restarts.

**Comment by shtefcs** [comment]
Thank you for implementing this, we had the same problem crashing our whole app. Lets see how this improvement will work.

Peace
