### ISSUE TITLE
not found grease

### ISSUE THREAD

**Issue by tagMatrix4** [Danny-Dasilva/CycleTLS#53]
src: https://tools.ietf.org/id/draft-davidben-tls-grease-00.html
Call the website and return 403. The packet capture data is as follows:
charles-cycletls:
![1](https://user-images.githubusercontent.com/25616829/137847956-071269f9-a0cb-4c5b-b16e-59b40b0b5706.png)

charles-google browser:
![2](https://user-images.githubusercontent.com/25616829/137847975-2d426e15-8876-402c-b2e8-b05f98af5481.png)

The same problem exists in Cipher Suite array

**Comment by Danny-Dasilva** [comment]
Feel free to test `0.0.15-alpha.0` alpha branch, it should have grease re-enabled. Expect a fix in a coming release soon

**Comment by Tkd-Alex** [comment]
> Feel free to test `0.0.15-alpha.0` alpha branch, it should have grease re-enabled. Expect a fix in a coming release soon

It's possible that I can't find this branch?

**Comment by Danny-Dasilva** [comment]
Grease Extensions should be properly implemented as of [this release](https://github.com/Danny-Dasilva/CycleTLS/pull/91) and a few fhttp updates. Let me know if any new issues appear or if anything is not as expected.
