### ISSUE TITLE
Headers are not being applied

### ISSUE THREAD

**Issue by clouedoc** [Danny-Dasilva/CycleTLS#60]
**Actual behavior**

Headers specified in `cycletls.Options` are not applied using the Go library.

**Expected behavior**

`https://httpbin.org/headers` should return the additional header (`foo`)

**To Reproduce** Steps to reproduce the behavior

```go
r, err := client.Do("https://httpbin.org/headers", cycletls.Options{
		Ja3:       fp.Ja3,
		UserAgent: fp.UserAgent,
		Headers:   map[string]string{
                     "foo": "bar",
                },
	}, opts.Method)
```

**Additional Information**

-   Operating System information: Darwin Big Sur 11.6
-   Node version: N/A
-   Golang version: `go1.17.6 darwin/arm64`

### `go.mod`

```txt
github.com/Danny-Dasilva/CycleTLS/cycletls v0.0.0-20220211211237-3f5cc5690340 // indirect
github.com/Danny-Dasilva/fhttp v0.0.0-20211010093114-56fde831fe2f // indirect
```

**Comment by 89z** [comment]
For an alternative, you can build your request as normal, and only use JA3 with the transport layer:

~~~go
package tls

import (
   "github.com/89z/format/crypto"
   "net/http"
)

func roundTrip(req *http.Request) (*http.Response, error) {
   hello, err := crypto.ParseJA3(crypto.AndroidAPI29)
   if err != nil {
      return nil, err
   }
   return crypto.Transport(hello).RoundTrip(req)
}
~~~

Result:

~~~json
{
  "headers": {
    "Accept-Encoding": "gzip",
    "Foo": "bar",
    "Host": "httpbin.org",
    "User-Agent": "hello world",
    "X-Amzn-Trace-Id": "Root=1-620b3194-19b5ec6c599b455c24d47a30"
  }
}
~~~

**Comment by Danny-Dasilva** [comment]
Great catch, should be fixed in the [latest release](https://github.com/Danny-Dasilva/CycleTLS/pull/61) 0.0.16. I added tests to cover this as well.

**Comment by clouedoc** [comment]
@89z @Danny-Dasilva 

Thank you for both of your answers 🙏
