### ISSUE TITLE
My Chrome TLS Fingerprint is giving error :  error: remote error: tls: error decoding message map[]

### ISSUE THREAD

**Issue by amitmisratas** [Danny-Dasilva/CycleTLS#64]
My current chrome fingerprint i.e. 771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,0-23-65281-10-11-35-16-5-13-18-51-45-43-27-21,,

Is failing with this error error: remote error: tls: error decoding message map[]

It looks like last two parameters of my ja3 fingerprint are blank... and with those two blank, I am getting this error. If I fill those two parameters also with some previous value like 29-23-24,0 

Then I stop getting this error and it works fine for me... But right now I am getting both of those values blank in Chrome, Firefox as well as Edge... 

Can somebody please help me what I am missing out on?

**Comment by 89z** [comment]
> My current chrome fingerprint i.e. 771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,0-23-65281-10-11-35-16-5-13-18-51-45-43-27-21,,

No, that is not your fingerprint. As mentioned several times before, you cannot have empty EllipticCurve with SSLExtension 10, and you cannot have empty EllipticCurvePointFormat with SSLExtension 11. So whatever tool you used to create the fingerprint, is not valid.

**Comment by amitmisratas** [comment]
Oh... Thanks a lot. I was struggling with this issue for a couple of days. That's not a problem in that case...

**Comment by 89z** [comment]
https://github.com/salesforce/ja3/issues/71
