### ISSUE TITLE
Not Able to Read Cookies in the redirected requests...

### ISSUE THREAD

**Issue by amitmisratas** [Danny-Dasilva/CycleTLS#66]
I am able to get cookies from a request that is being generated by a redirect... Here is the scenario...

1. I hit URL1... URL1 sends back 2 cookies and then Redirects to URL2.
2. URL2 opens without any cookies...

Now I am not able to get any cookies if I set disableRedirect to false. And I am not getting redirected if I set disableRedirect to True...

What should be done in this case?

**Comment by 89z** [comment]
is this issue specific to this repo? Couldnt you just use `crypto/tls` for this?

**Comment by amitmisratas** [comment]
Sorry, don't get you... What do you mean by using crypto/TLS directly?

When I use cycletls directly... It redirects but does not show those
cookies...
