### ISSUE TITLE
Extension {{ 17513 }} is not Supported

### ISSUE THREAD

**Issue by White2001Offl** [Danny-Dasilva/CycleTLS#70]
### Description

I get this `Extension {{ 17513 }} is not Supported` from this JA3 `771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,0-23-65281-10-11-35-16-5-13-18-51-45-43-27-17513,29-23-24,0`

### Issue Type

Support

### Operating System

Windows 10, Mac OS

### Node Version

Node 16.x

### Golang Version

Go 16.x

### Relevant Log Output

```shell
-> \nGet \"https://ja3er.com/json\": Extension {{ 17513 }} is not Supported by CycleTLS please raise an issue
```

**Comment by 89z** [comment]
Given that 17513 is unassigned [1], and that JA3er.com was involved, I would recommend this issue be closed. As mentioned in other issues. JA3er.com is a poisoned source of information regarding JA3, as its known to produce provably invalid fingerprints.

1. https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml

**Comment by Danny-Dasilva** [comment]
@89z Do you know of a more reputable site for pulling ja3 hashes, ideally one that's open source or a good method to implement that. Happy to spend the time developing this because I agree, ja3er is pointing people in the wrong direction and is often causing more issues.

**Comment by 89z** [comment]
Sadly I think we would need to host our own. I am willing to help if you need any coding help. I think you can host free Go servers on https://replit.com, or if you have a better idea thats cool.

**Comment by Danny-Dasilva** [comment]
Good to know, I'll look into creating something. Most likely a normal and HTTP/2 version of the site is needed. I'll reach out if I need anything.

**Comment by cuteacc** [comment]
Hello, this is the JA3 fingerprint of Google Chrome. This extension is not IANA assigned, but comes from BoringSSL. It is known as "extensionApplicationSettings"

**Comment by 89z** [comment]
> Hello, this is the JA3 fingerprint of Google Chrome. This extension is not IANA assigned, but comes from [BoringSSL](https://github.com/google/boringssl). It is known as "extensionApplicationSettings" in the code.

@cuteacc please link directly to the code in question. Please don't make other people find their own references.

@Danny-Dasilva in these cases, I add those as GenericExtension:

https://github.com/89z/format/blob/v1.29.6/crypto/parse.go#L102-L108

although again, I wouldn't make any change until we have a proper reference, which we don't yet.

**Comment by cuteacc** [comment]
> > Hello, this is the JA3 fingerprint of Google Chrome. This extension is not IANA assigned, but comes from [BoringSSL](https://github.com/google/boringssl). It is known as "extensionApplicationSettings" in the code.
> 
> @cuteacc please link directly to the code in question. Please don't make other people find their own references.
> 
> @Danny-Dasilva in these cases, I add those as GenericExtension:
> 
> https://github.com/89z/format/blob/v1.29.6/crypto/parse.go#L102-L108
> 
> although again, I wouldn't make any change until we have a proper reference, which we don't yet.

Apologies, [this](https://github.com/google/boringssl/blob/18b6836b2f6340187a7981c82be9be9d092d36d6/ssl/test/runner/common.go#L125) is where it is defined as  `17513`, and [here](https://github.com/google/boringssl/blob/18b6836b2f6340187a7981c82be9be9d092d36d6/ssl/test/runner/handshake_messages.go#L1190) is their implementation of it. It is for [ALPS](https://www.ietf.org/archive/id/draft-vvv-httpbis-alps-01.html), a HTTP/2 and HTTP/3 feature.

**Comment by 89z** [comment]
The user of the last two comments has deleted their account:

https://github.com/cuteacc

so, regardless of any comment they have made, I would recommend no changes at this time. It appears the person has suspect motives.

**Comment by Danny-Dasilva** [comment]
Extension 17513 is now supported as of [this release](https://github.com/Danny-Dasilva/CycleTLS/pull/91). Ja3er does not properly return this extension due to it's [known issues](https://github.com/Danny-Dasilva/CycleTLS/issues/39#issuecomment-922154225). However sites like https://tls.peet.ws/api/clean and Wireshark should verify that we are returning `17513`.

**Comment by 89z** [comment]
@Danny-Dasilva that site is pretty cool. Do you have a specification for the Akamai fingerprint?

**Comment by Danny-Dasilva** [comment]
I do not, looking into how to implement this though

**Comment by 89z** [comment]
found it:

 https://blackhat.com/docs/eu-17/materials/eu-17-Shuster-Passive-Fingerprinting-Of-HTTP2-Clients-wp.pdf

**Comment by 89z** [comment]
https://github.com/Danny-Dasilva/CycleTLS/issues/94

**Comment by Danny-Dasilva** [comment]
Thanks for this, I'll most likely modify this to run tests against internally

**Comment by 89z** [comment]
FYI, I spoke with developer for https://tls.peet.ws - they have open sourced that server as well:

https://github.com/wwhtrbbtt/TrackMe

**Comment by Danny-Dasilva** [comment]
> FYI, I spoke with developer for https://tls.peet.ws - they have open sourced that server as well:
> 
> https://github.com/wwhtrbbtt/TrackMe

Thanks a lot, super appreciated 👍

**Comment by 89z** [comment]
Not sure if you are still interested in knowing about other servers, but I found another open source one. This is in C#, so might not be useful:

https://github.com/yuzd/ja3-csharp
