### ISSUE TITLE
Support Socks5/4

### ISSUE THREAD

**Issue by obfuscatus** [Danny-Dasilva/CycleTLS#77]
Hi there,
Please support socks5 feature to proxy. I tried 'proxy: 'socks5://127.0.0.1:1080' but seems like it does not supported right now.
Output:

`scheme socks5 is not supported`

**Comment by Xaopinga** [comment]
I set up the Http proxy and error "unexpected EOF"

**Comment by Danny-Dasilva** [comment]
this should now be supported in version [1.0.22](https://github.com/Danny-Dasilva/CycleTLS/pull/266)

**Comment by rdtmaster** [comment]
@Danny-Dasilva
still does not work with go version of the package. Fails with ```scheme socks5 is not supported``` error (tried with ```socks``` scheme as well)
