### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by psdp** [Danny-Dasilva/CycleTLS#81]
Hi, I can build the binary file for Linux ARM64 with flag `GOARCH=arm64`, but it doesn't seem to work. Keeps getting this error `listen tcp :9119: bind: address already in use`

Is there any plan to support ARM64?

**Comment by White2001Offl** [comment]
It means another process running which is listening on that port 9119
Check your process list and terminate it. Then retry

**Comment by psdp** [comment]
Yes, I've checked the the port is opened and used by CycleTLS only, so it's weird to see this error. It only happens to the custom Linux ARM64 build I created, couldn't reproduce it on my other linux X64 machine.

**Comment by Danny-Dasilva** [comment]
You can configure a custom port like this 

```js
const cycleTLS = await initCycleTLS({ port: 9116 });
```

Arm compilation is not natively supported currently but I can add it into the package.

**Comment by psdp** [comment]
Got it. Thanks @Danny-Dasilva

**Comment by carmolim** [comment]
I'm using an m1 mac with arm64 I can try any port I want, but I always get this error message: 

```
Error Processing Request (please open an issue https://github.com/Danny-Dasilva/CycleTLS/issues/new/choose) -> 2023/12/19 08:56:25 listen tcp :XXXX: bind: address already in use
```

Is it possible to run this run the cycletls on arm64?
