### ISSUE TITLE
builder error

### ISSUE THREAD

**Issue by tagMatrix4** [Danny-Dasilva/CycleTLS#82]
`c:\\tls\CycleTLS>go get -u -v github.com/Danny-Dasilva/CycleTLS/cycletls
github.com\Danny-Dasilva\CycleTLS (download)
github.com\Danny-Dasilva\fhttp (download)
# cd .; git ls-remote https://gitlab.com/yawning/utls
fatal: Cannot prompt because user interactivity has been disabled.
fatal: could not read Username for 'https://gitlab.com': terminal prompts disabled
# cd .; git ls-remote git+ssh://gitlab.com/yawning/utls
Host key verification failed.
fatal: Could not read from remote repository.
`

**Comment by Danny-Dasilva** [comment]
Dependencies updated in release [0.0.19](https://github.com/Danny-Dasilva/CycleTLS/pull/87)
`go get -u github.com/Danny-Dasilva/CycleTLS/cycletls` should work
