### ISSUE TITLE
Custom utls dependency for golang proxy tool unavailable

### ISSUE THREAD

**Issue by zebrapurring** [Danny-Dasilva/CycleTLS#84]
**Actual behavior** Unable to build the golang proxy tool due to private dependencies.

**To Reproduce** Steps to reproduce the behavior

1.  `go env -w GO111MODULE=auto`
2.  `go get github.com/Danny-Dasilva/CycleTLS/cycletls` returns error `package gitlab.com/yawning/utls.git: cannot download, git://gitlab.com/yawning/utls uses insecure protocol`

**Additional Information**

-   Operating System information: macOS 12.3 Monterey on arm64
-   Node version: v16.14.2
-   Golang version: go1.18.1 darwin/arm64

**Comment by Danny-Dasilva** [comment]
Dependencies updated in release [0.0.19](https://github.com/Danny-Dasilva/CycleTLS/pull/87)
`go get -u github.com/Danny-Dasilva/CycleTLS/cycletls` should work
