### ISSUE TITLE
Duplicate sources for the golang proxy tool

### ISSUE THREAD

**Issue by zebrapurring** [Danny-Dasilva/CycleTLS#85]
I noticed the golang proxy tool sources are duplicated inside the [cycletls](https://github.com/Danny-Dasilva/CycleTLS/tree/3bf5719977c5a556e61774b994822f45088253cd/cycletls) and the [golang](https://github.com/Danny-Dasilva/CycleTLS/tree/3bf5719977c5a556e61774b994822f45088253cd/golang) directories (except for the package name).

Is there a reason for maintaining both duplicate directores?

**Comment by Danny-Dasilva** [comment]
Yes, one is functionally an src folder that gets compiled down for running in JavaScript/Ts. The other one is a golang module. This gives users access to the underlying golang package and all the corresponding methods in a way that is installable via Golang. 

E.g. `go get github.com/Danny-Dasilva/CycleTLS/cycletls`

I can look into how I would combine these, there are tests to make sure the files are identical. The main difference is module namespacing for Golang.

**Comment by zebrapurring** [comment]
Would be great to unify them, this would keep the repo simpler and cleaner. Thanks!

**Comment by Danny-Dasilva** [comment]
As far as I am aware currently there is no way to compile and execute a non `main` package. Basically executable commands must always use package `main` as the entry point for executables is `main.main`. 

Open to suggestions for how to compile non-main packages which would solve this issue. 

Either we lose the ability to compile/run the golang process for Js/Ts or we lose the ability for Go developers to install and use the base package.

**Comment by zebrapurring** [comment]
I see... I don't have much experience with Go, but would it be possible to maintain the `cycletls` package as a library, and keep a smaller `main` package which imports `cycletls` and only contains the `main` function (which is not needed for the library)?

I tried to implement it this way, but am currently unable to build the package due to the missing dependencies from #84.

**Comment by Danny-Dasilva** [comment]
This implementation is a good idea, I will try to implement this on the next release

**Comment by Danny-Dasilva** [comment]
Sources are now combined as of [this release](https://github.com/Danny-Dasilva/CycleTLS/pull/91).
