### ISSUE TITLE
How to post ContentType multipart/form-data?

### ISSUE THREAD

**Issue by xualen** [Danny-Dasilva/CycleTLS#89]
### Description

How to post ContentType multipart/form-data?

### Issue Type

Support

### Operating System

Windows 10

### Golang Version

Go 17.x

**Comment by Danny-Dasilva** [comment]
I'll get this added in the next release

**Comment by Gorge123** [comment]
> I'll get this added in the next release
When it will be available? Very need this ability. Thanks!

**Comment by xtdmcn** [comment]
import (
	"github.com/Danny-Dasilva/CycleTLS/cycletls"
	"mime/multipart"
)
opt := cycletls.Options{}
buf := new(bytes.Buffer)
bodywriter := multipart.NewWriter(buf)
bodywriter.WriteField("name", "aaaaa")
defer bodywriter.Close()
opt.Body = buf.String()
var head map[string]string
head["Content-Type"] = bodywriter.FormDataContentType()
opt.Headers = head
client := cycletls.Init()
r, err := client.Do(url, opt, "get")

**Comment by Danny-Dasilva** [comment]
Official support added in the latest release 

https://github.com/Danny-Dasilva/CycleTLS#how-do-i-send-multipartform-data-in-cycletls
