### ISSUE TITLE
presharedkey Extension support.

### ISSUE THREAD

**Issue by rezoners** [Danny-Dasilva/CycleTLS#93]
Right now i see using extension "41" pre_shared_key is not possible. But there are some severs that checks them.

I didn't find if even in native go client there is support for that.

**Comment by Danny-Dasilva** [comment]
Pre Shared Key is now supported with the latest release
https://github.com/Danny-Dasilva/CycleTLS/blob/f6c898f1bb298f3d6dd7fcfdfb531d950cc587a3/cycletls/utils.go#L294-L303
