### ISSUE TITLE
Ja3er is no longer up how can we obtain our Ja3 hash?

### ISSUE THREAD

**Issue by dracoDevs** [Danny-Dasilva/CycleTLS#99]

**Comment by Danny-Dasilva** [comment]
There are a couple ways. One is external sites such as https://tls.fxnatic.dev/api/fp, https://tlshello.agwa.name/ or https://tls.peet.ws/all/. Alternatively (probably preferred) is to run a fingerprinting site locally https://github.com/wwhtrbbtt/TrackMe. I will have one available and built into this repo shortly.

**Comment by dracoDevs** [comment]
> There are a couple ways. One is external sites such as https://tls.fxnatic.dev/api/fp, https://tlshello.agwa.name/ or https://tls.peet.ws/all/. Alternatively (probably preferred) is to run a fingerprinting site locally https://github.com/wwhtrbbtt/TrackMe. I will have one available and built into this repo shortly.

Thanks for the quick reply!

**Comment by dracoDevs** [comment]
Thanks for such a quick reply!
@Danny-Dasilva
